// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test0715.proto

#include "test0715.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace myPackage {
constexpr DATA::DATA(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : x_axis_(0)
  , y_axis_(0){}
struct DATADefaultTypeInternal {
  constexpr DATADefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~DATADefaultTypeInternal() {}
  union {
    DATA _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT DATADefaultTypeInternal _DATA_default_instance_;
constexpr DATAPACK::DATAPACK(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : data_()
  , cmd_(0u){}
struct DATAPACKDefaultTypeInternal {
  constexpr DATAPACKDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~DATAPACKDefaultTypeInternal() {}
  union {
    DATAPACK _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT DATAPACKDefaultTypeInternal _DATAPACK_default_instance_;
}  // namespace myPackage
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_test0715_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_test0715_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_test0715_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_test0715_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::myPackage::DATA, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::myPackage::DATA, x_axis_),
  PROTOBUF_FIELD_OFFSET(::myPackage::DATA, y_axis_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::myPackage::DATAPACK, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::myPackage::DATAPACK, cmd_),
  PROTOBUF_FIELD_OFFSET(::myPackage::DATAPACK, data_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::myPackage::DATA)},
  { 7, -1, sizeof(::myPackage::DATAPACK)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::myPackage::_DATA_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::myPackage::_DATAPACK_default_instance_),
};

const char descriptor_table_protodef_test0715_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016test0715.proto\022\tmyPackage\"&\n\004DATA\022\016\n\006x"
  "_axis\030\001 \001(\001\022\016\n\006y_axis\030\002 \001(\001\"6\n\010DATAPACK\022"
  "\013\n\003cmd\030\001 \001(\r\022\035\n\004data\030\002 \003(\0132\017.myPackage.D"
  "ATAb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_test0715_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_test0715_2eproto = {
  false, false, 131, descriptor_table_protodef_test0715_2eproto, "test0715.proto", 
  &descriptor_table_test0715_2eproto_once, nullptr, 0, 2,
  schemas, file_default_instances, TableStruct_test0715_2eproto::offsets,
  file_level_metadata_test0715_2eproto, file_level_enum_descriptors_test0715_2eproto, file_level_service_descriptors_test0715_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_test0715_2eproto_getter() {
  return &descriptor_table_test0715_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_test0715_2eproto(&descriptor_table_test0715_2eproto);
namespace myPackage {

// ===================================================================

class DATA::_Internal {
 public:
};

DATA::DATA(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:myPackage.DATA)
}
DATA::DATA(const DATA& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&x_axis_, &from.x_axis_,
    static_cast<size_t>(reinterpret_cast<char*>(&y_axis_) -
    reinterpret_cast<char*>(&x_axis_)) + sizeof(y_axis_));
  // @@protoc_insertion_point(copy_constructor:myPackage.DATA)
}

inline void DATA::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&x_axis_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&y_axis_) -
    reinterpret_cast<char*>(&x_axis_)) + sizeof(y_axis_));
}

DATA::~DATA() {
  // @@protoc_insertion_point(destructor:myPackage.DATA)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void DATA::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DATA::ArenaDtor(void* object) {
  DATA* _this = reinterpret_cast< DATA* >(object);
  (void)_this;
}
void DATA::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DATA::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void DATA::Clear() {
// @@protoc_insertion_point(message_clear_start:myPackage.DATA)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_axis_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&y_axis_) -
      reinterpret_cast<char*>(&x_axis_)) + sizeof(y_axis_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DATA::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double x_axis = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          x_axis_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // double y_axis = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          y_axis_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DATA::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:myPackage.DATA)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double x_axis = 1;
  if (!(this->_internal_x_axis() <= 0 && this->_internal_x_axis() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_x_axis(), target);
  }

  // double y_axis = 2;
  if (!(this->_internal_y_axis() <= 0 && this->_internal_y_axis() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_y_axis(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myPackage.DATA)
  return target;
}

size_t DATA::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:myPackage.DATA)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double x_axis = 1;
  if (!(this->_internal_x_axis() <= 0 && this->_internal_x_axis() >= 0)) {
    total_size += 1 + 8;
  }

  // double y_axis = 2;
  if (!(this->_internal_y_axis() <= 0 && this->_internal_y_axis() >= 0)) {
    total_size += 1 + 8;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DATA::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    DATA::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DATA::GetClassData() const { return &_class_data_; }

void DATA::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<DATA *>(to)->MergeFrom(
      static_cast<const DATA &>(from));
}


void DATA::MergeFrom(const DATA& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:myPackage.DATA)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from._internal_x_axis() <= 0 && from._internal_x_axis() >= 0)) {
    _internal_set_x_axis(from._internal_x_axis());
  }
  if (!(from._internal_y_axis() <= 0 && from._internal_y_axis() >= 0)) {
    _internal_set_y_axis(from._internal_y_axis());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DATA::CopyFrom(const DATA& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:myPackage.DATA)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DATA::IsInitialized() const {
  return true;
}

void DATA::InternalSwap(DATA* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DATA, y_axis_)
      + sizeof(DATA::y_axis_)
      - PROTOBUF_FIELD_OFFSET(DATA, x_axis_)>(
          reinterpret_cast<char*>(&x_axis_),
          reinterpret_cast<char*>(&other->x_axis_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DATA::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_test0715_2eproto_getter, &descriptor_table_test0715_2eproto_once,
      file_level_metadata_test0715_2eproto[0]);
}

// ===================================================================

class DATAPACK::_Internal {
 public:
};

DATAPACK::DATAPACK(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  data_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:myPackage.DATAPACK)
}
DATAPACK::DATAPACK(const DATAPACK& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      data_(from.data_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  cmd_ = from.cmd_;
  // @@protoc_insertion_point(copy_constructor:myPackage.DATAPACK)
}

inline void DATAPACK::SharedCtor() {
cmd_ = 0u;
}

DATAPACK::~DATAPACK() {
  // @@protoc_insertion_point(destructor:myPackage.DATAPACK)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void DATAPACK::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DATAPACK::ArenaDtor(void* object) {
  DATAPACK* _this = reinterpret_cast< DATAPACK* >(object);
  (void)_this;
}
void DATAPACK::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void DATAPACK::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void DATAPACK::Clear() {
// @@protoc_insertion_point(message_clear_start:myPackage.DATAPACK)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  cmd_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DATAPACK::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 cmd = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          cmd_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .myPackage.DATA data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_data(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* DATAPACK::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:myPackage.DATAPACK)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 cmd = 1;
  if (this->_internal_cmd() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_cmd(), target);
  }

  // repeated .myPackage.DATA data = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_data_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_data(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myPackage.DATAPACK)
  return target;
}

size_t DATAPACK::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:myPackage.DATAPACK)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .myPackage.DATA data = 2;
  total_size += 1UL * this->_internal_data_size();
  for (const auto& msg : this->data_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 cmd = 1;
  if (this->_internal_cmd() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_cmd());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DATAPACK::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    DATAPACK::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DATAPACK::GetClassData() const { return &_class_data_; }

void DATAPACK::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<DATAPACK *>(to)->MergeFrom(
      static_cast<const DATAPACK &>(from));
}


void DATAPACK::MergeFrom(const DATAPACK& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:myPackage.DATAPACK)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
  if (from._internal_cmd() != 0) {
    _internal_set_cmd(from._internal_cmd());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DATAPACK::CopyFrom(const DATAPACK& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:myPackage.DATAPACK)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DATAPACK::IsInitialized() const {
  return true;
}

void DATAPACK::InternalSwap(DATAPACK* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  data_.InternalSwap(&other->data_);
  swap(cmd_, other->cmd_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DATAPACK::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_test0715_2eproto_getter, &descriptor_table_test0715_2eproto_once,
      file_level_metadata_test0715_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace myPackage
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::myPackage::DATA* Arena::CreateMaybeMessage< ::myPackage::DATA >(Arena* arena) {
  return Arena::CreateMessageInternal< ::myPackage::DATA >(arena);
}
template<> PROTOBUF_NOINLINE ::myPackage::DATAPACK* Arena::CreateMaybeMessage< ::myPackage::DATAPACK >(Arena* arena) {
  return Arena::CreateMessageInternal< ::myPackage::DATAPACK >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
