// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fakePB.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_fakePB_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_fakePB_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_fakePB_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_fakePB_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_fakePB_2eproto;
namespace myFakePb {
class ACC_DATA;
struct ACC_DATADefaultTypeInternal;
extern ACC_DATADefaultTypeInternal _ACC_DATA_default_instance_;
class DATAPACK;
struct DATAPACKDefaultTypeInternal;
extern DATAPACKDefaultTypeInternal _DATAPACK_default_instance_;
}  // namespace myFakePb
PROTOBUF_NAMESPACE_OPEN
template<> ::myFakePb::ACC_DATA* Arena::CreateMaybeMessage<::myFakePb::ACC_DATA>(Arena*);
template<> ::myFakePb::DATAPACK* Arena::CreateMaybeMessage<::myFakePb::DATAPACK>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace myFakePb {

// ===================================================================

class ACC_DATA final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:myFakePb.ACC_DATA) */ {
 public:
  inline ACC_DATA() : ACC_DATA(nullptr) {}
  ~ACC_DATA() override;
  explicit constexpr ACC_DATA(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ACC_DATA(const ACC_DATA& from);
  ACC_DATA(ACC_DATA&& from) noexcept
    : ACC_DATA() {
    *this = ::std::move(from);
  }

  inline ACC_DATA& operator=(const ACC_DATA& from) {
    CopyFrom(from);
    return *this;
  }
  inline ACC_DATA& operator=(ACC_DATA&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ACC_DATA& default_instance() {
    return *internal_default_instance();
  }
  static inline const ACC_DATA* internal_default_instance() {
    return reinterpret_cast<const ACC_DATA*>(
               &_ACC_DATA_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ACC_DATA& a, ACC_DATA& b) {
    a.Swap(&b);
  }
  inline void Swap(ACC_DATA* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ACC_DATA* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ACC_DATA* New() const final {
    return new ACC_DATA();
  }

  ACC_DATA* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ACC_DATA>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ACC_DATA& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ACC_DATA& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ACC_DATA* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "myFakePb.ACC_DATA";
  }
  protected:
  explicit ACC_DATA(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXAxisFieldNumber = 1,
    kYAxisFieldNumber = 2,
    kZAxisFieldNumber = 3,
  };
  // int32 x_axis = 1;
  void clear_x_axis();
  ::PROTOBUF_NAMESPACE_ID::int32 x_axis() const;
  void set_x_axis(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_x_axis() const;
  void _internal_set_x_axis(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 y_axis = 2;
  void clear_y_axis();
  ::PROTOBUF_NAMESPACE_ID::int32 y_axis() const;
  void set_y_axis(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_y_axis() const;
  void _internal_set_y_axis(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 z_axis = 3;
  void clear_z_axis();
  ::PROTOBUF_NAMESPACE_ID::int32 z_axis() const;
  void set_z_axis(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_z_axis() const;
  void _internal_set_z_axis(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:myFakePb.ACC_DATA)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 x_axis_;
  ::PROTOBUF_NAMESPACE_ID::int32 y_axis_;
  ::PROTOBUF_NAMESPACE_ID::int32 z_axis_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_fakePB_2eproto;
};
// -------------------------------------------------------------------

class DATAPACK final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:myFakePb.DATAPACK) */ {
 public:
  inline DATAPACK() : DATAPACK(nullptr) {}
  ~DATAPACK() override;
  explicit constexpr DATAPACK(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DATAPACK(const DATAPACK& from);
  DATAPACK(DATAPACK&& from) noexcept
    : DATAPACK() {
    *this = ::std::move(from);
  }

  inline DATAPACK& operator=(const DATAPACK& from) {
    CopyFrom(from);
    return *this;
  }
  inline DATAPACK& operator=(DATAPACK&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DATAPACK& default_instance() {
    return *internal_default_instance();
  }
  static inline const DATAPACK* internal_default_instance() {
    return reinterpret_cast<const DATAPACK*>(
               &_DATAPACK_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(DATAPACK& a, DATAPACK& b) {
    a.Swap(&b);
  }
  inline void Swap(DATAPACK* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DATAPACK* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline DATAPACK* New() const final {
    return new DATAPACK();
  }

  DATAPACK* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<DATAPACK>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DATAPACK& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const DATAPACK& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DATAPACK* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "myFakePb.DATAPACK";
  }
  protected:
  explicit DATAPACK(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 2,
    kCmdFieldNumber = 1,
  };
  // repeated .myFakePb.ACC_DATA data = 2;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  ::myFakePb::ACC_DATA* mutable_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::myFakePb::ACC_DATA >*
      mutable_data();
  private:
  const ::myFakePb::ACC_DATA& _internal_data(int index) const;
  ::myFakePb::ACC_DATA* _internal_add_data();
  public:
  const ::myFakePb::ACC_DATA& data(int index) const;
  ::myFakePb::ACC_DATA* add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::myFakePb::ACC_DATA >&
      data() const;

  // uint32 cmd = 1;
  void clear_cmd();
  ::PROTOBUF_NAMESPACE_ID::uint32 cmd() const;
  void set_cmd(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_cmd() const;
  void _internal_set_cmd(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:myFakePb.DATAPACK)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::myFakePb::ACC_DATA > data_;
  ::PROTOBUF_NAMESPACE_ID::uint32 cmd_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_fakePB_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ACC_DATA

// int32 x_axis = 1;
inline void ACC_DATA::clear_x_axis() {
  x_axis_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ACC_DATA::_internal_x_axis() const {
  return x_axis_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ACC_DATA::x_axis() const {
  // @@protoc_insertion_point(field_get:myFakePb.ACC_DATA.x_axis)
  return _internal_x_axis();
}
inline void ACC_DATA::_internal_set_x_axis(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  x_axis_ = value;
}
inline void ACC_DATA::set_x_axis(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_x_axis(value);
  // @@protoc_insertion_point(field_set:myFakePb.ACC_DATA.x_axis)
}

// int32 y_axis = 2;
inline void ACC_DATA::clear_y_axis() {
  y_axis_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ACC_DATA::_internal_y_axis() const {
  return y_axis_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ACC_DATA::y_axis() const {
  // @@protoc_insertion_point(field_get:myFakePb.ACC_DATA.y_axis)
  return _internal_y_axis();
}
inline void ACC_DATA::_internal_set_y_axis(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  y_axis_ = value;
}
inline void ACC_DATA::set_y_axis(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_y_axis(value);
  // @@protoc_insertion_point(field_set:myFakePb.ACC_DATA.y_axis)
}

// int32 z_axis = 3;
inline void ACC_DATA::clear_z_axis() {
  z_axis_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ACC_DATA::_internal_z_axis() const {
  return z_axis_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ACC_DATA::z_axis() const {
  // @@protoc_insertion_point(field_get:myFakePb.ACC_DATA.z_axis)
  return _internal_z_axis();
}
inline void ACC_DATA::_internal_set_z_axis(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  z_axis_ = value;
}
inline void ACC_DATA::set_z_axis(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_z_axis(value);
  // @@protoc_insertion_point(field_set:myFakePb.ACC_DATA.z_axis)
}

// -------------------------------------------------------------------

// DATAPACK

// uint32 cmd = 1;
inline void DATAPACK::clear_cmd() {
  cmd_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DATAPACK::_internal_cmd() const {
  return cmd_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 DATAPACK::cmd() const {
  // @@protoc_insertion_point(field_get:myFakePb.DATAPACK.cmd)
  return _internal_cmd();
}
inline void DATAPACK::_internal_set_cmd(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  cmd_ = value;
}
inline void DATAPACK::set_cmd(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_cmd(value);
  // @@protoc_insertion_point(field_set:myFakePb.DATAPACK.cmd)
}

// repeated .myFakePb.ACC_DATA data = 2;
inline int DATAPACK::_internal_data_size() const {
  return data_.size();
}
inline int DATAPACK::data_size() const {
  return _internal_data_size();
}
inline void DATAPACK::clear_data() {
  data_.Clear();
}
inline ::myFakePb::ACC_DATA* DATAPACK::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:myFakePb.DATAPACK.data)
  return data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::myFakePb::ACC_DATA >*
DATAPACK::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:myFakePb.DATAPACK.data)
  return &data_;
}
inline const ::myFakePb::ACC_DATA& DATAPACK::_internal_data(int index) const {
  return data_.Get(index);
}
inline const ::myFakePb::ACC_DATA& DATAPACK::data(int index) const {
  // @@protoc_insertion_point(field_get:myFakePb.DATAPACK.data)
  return _internal_data(index);
}
inline ::myFakePb::ACC_DATA* DATAPACK::_internal_add_data() {
  return data_.Add();
}
inline ::myFakePb::ACC_DATA* DATAPACK::add_data() {
  ::myFakePb::ACC_DATA* _add = _internal_add_data();
  // @@protoc_insertion_point(field_add:myFakePb.DATAPACK.data)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::myFakePb::ACC_DATA >&
DATAPACK::data() const {
  // @@protoc_insertion_point(field_list:myFakePb.DATAPACK.data)
  return data_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace myFakePb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_fakePB_2eproto
